### ISSUE TITLE
READ THIS BEFORE OPENING AN ISSUE!

### ISSUE THREAD

**Issue by adolfintel** [librespeed/speedtest-android#1]
__When you should open an issue:__
- You want a feature added
- You found a bug (for instance, a parameter not being parsed correctly, or the test not working on a system that should be supported)
- Suggestions for improving a feature
- You want to discuss a design choice or want to know more about something regarding the test

__When you should NOT open an issue:__
- If you need troubleshooting. Contact me at [info@fdossena.com](mailto:info@fdossena.com).

__If you open an issue:__
- Try to describe your problem/suggestion thoroughly
- For a bug report, I need to know about your server (OS, server, configuration, network, ...) as well as your client (Model and OS at least). Post screenshots if necessary.

**Comment by LinuxOnTheDesktop** [comment]
It seems confusing to me to have an issue that is both pinned and closed. Indeed, it seems the issue was pinned and closed _on the same day_.
