### ISSUE TITLE
Speedtest Server dont work correctly in the app (Subfolders)

### ISSUE THREAD

**Issue by Xenic28** [librespeed/speedtest-android#11]

**Comment by Xenic28** [comment]
Hey have at the moment the issue thats the app dont make an speedtest if i click the button then the speedtest dont start then the app goes back into the selcection of the app. Without an Subfolder the App Works perfect. With an subfolder the app dont start correct an speedtest.
Please fix this 
Thanks Xenic.

**Comment by adolfintel** [comment]
I don't understand your post.
Subfolders where? In the app? On the server? Can you show me your config files?

**Comment by Xenic28** [comment]
On my Server are the files in an Subfolder and if i open the APP and make an speedtest the app dont start correct the speedtest and the app goes again into the selection menü.
Thanks for Help Xenic

**Comment by adolfintel** [comment]
The app supports it so it's probably a config error. Send me your ServerList.json file so I can test it. If you don't want to post it here, send it to info@fdossena.com
