### ISSUE TITLE
Multi-data source download

### ISSUE THREAD

**Issue by Siychen92** [librespeed/speedtest-android#19]
Excuse me, I would like to ask you a question, yours is a single data source speed measurement, if I need multiple data sources to download speed measurement, what do I need to do

**Comment by adolfintel** [comment]
By single data source you mean that the test only uses one server at a time?

**Comment by Siychen92** [comment]
thanks, Yes,You're right,&nbsp;a single data source (one server) often limits the maximum download speed for each user, but my network bandwidth is very high, so I cannot measure the maximum network speed. So I want to download at a time through multiple data sources (such as three services) to get the maximum download speed.I don’t know if this is correct and how to improve on your basis


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "librespeed/speedtest-android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午4:36
收件人:&nbsp;"librespeed/speedtest-android"<speedtest-android@noreply.github.com&gt;;
抄送:&nbsp;"Dave·♞"<1219349950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest-android] Multi-data source download (#19)





 
By single data source you mean that the test only uses one server at a time?

**Comment by adolfintel** [comment]
LibreSpeed doesn't support it. iperf probably does.

**Comment by Siychen92** [comment]
OK, thanks a bunch. I hope iperf can help me




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "librespeed/speedtest-android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午4:53
收件人:&nbsp;"librespeed/speedtest-android"<speedtest-android@noreply.github.com&gt;;
抄送:&nbsp;"Dave·♞"<1219349950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest-android] Multi-data source download (#19)





 
LibreSpeed doesn't support it. iperf probably does.
