### ISSUE TITLE
movie

### ISSUE THREAD

**Issue by geraldolago1** [librespeed/speedtest-android#20]
is it possible to record a video teaching us how to configure the template and create the app? i tried all the ways via android studio and i have many errors in java

**Comment by adolfintel** [comment]
I'll do it if I have the time. Did you follow this? https://github.com/librespeed/speedtest-android/wiki/Configuring-the-template

What errors are you getting?

**Comment by geraldolago1** [comment]
![Sem título](https://user-images.githubusercontent.com/49870674/94640226-6c57e300-02b4-11eb-915f-dbdf7473a097.png)

**Comment by geraldolago1** [comment]
am i doing wrong?

**Comment by geraldolago1** [comment]
when i try build

**Comment by adolfintel** [comment]
That error is not from LibreSpeed, it's from android studio, I think you're missing part of the SDK, try redownloading it from SDK manager.
