### ISSUE TITLE
May I know speedtest config.json ?

### ISSUE THREAD

**Issue by bhoeyong** [librespeed/speedtest-android#24]
Hi ..may I know speedtestconfig.json how to put server list? Have Example?

**Comment by adolfintel** [comment]
This is the list used in our demo: https://librespeed.org/backend-servers/servers.php

Do not use these servers, they're for our demo

**Comment by bhoeyong** [comment]
Thanks ...I need find asia server....do u have singapore server?

**Comment by adolfintel** [comment]
We don't have servers in that area at the moment, but even if we did, they are not for public use, they are our demo servers.

**Comment by bhoeyong** [comment]
Ok, thanks.
