### ISSUE TITLE
Custom servers support

### ISSUE THREAD

**Issue by dimqua** [librespeed/speedtest-android#3]
Could you please add an option to specify your own server?

**Comment by adolfintel** [comment]
No, sorry.
This repo is meant as a template for administrators of LibreSpeed servers (like ISPs), so that they can create an android app that uses their test point(s).
If you have one or more LibreSpeed servers, the right thing to do is build your own app based on this template, configured to use your server(s).

**Comment by fazlerabbi37** [comment]
Hi @adolfintel. I found this while looking for an FOSS alternative to Speedtest by Ookla and this seems to be the only one that does speedtest well enough to compete with Speedtest by Ookla. While I understand your point that it is only a template for server admins, I urge you to understand that this is the only way for us to test speed with a FOSS app and reconsider it for implementation. Besides, I think the server admins will also be benefited from this feature if they want to have multiple server, and they don't have to recompile the app if they want to expand.

**Comment by Perflyst** [comment]
Stay tuned @fazlerabbi37! There is something in the works that is likely to make this issue less important here :)
If you are such a server admin and already host a speedtest backend or you are interested in hosting one, please contact me via email.

**Comment by fazlerabbi37** [comment]
> If you are such a server admin and already host a speedtest backend or you are interested in hosting one, please contact me via email.

unfortunately, I don't have any server to host a speedtest backend, but I would be sure to let anyone know who are interested. :smile:

**Comment by Morphy99** [comment]
> No, sorry.
> This repo is meant as a template for administrators of LibreSpeed servers (like ISPs), so that they can create an android app that uses their test point(s).
> If you have one or more LibreSpeed servers, the right thing to do is build your own app based on this template, configured to use your server(s).

Not everyone is well versed on building android APP's. Surely implementing a custom server address option would not affect the original use case? I'm looking at this app as a tool to test local wireless network throughput on different networks so the address of the LibreSpeed server would change on every use. Being able to scan for a local instance or even enter the IP would be so much more helpful than having to build an app each time for each network it's used on.
