### ISSUE TITLE
Configuration error: Failed to load server list

### ISSUE THREAD

**Issue by mrtaxi** [librespeed/speedtest-android#42]
Librespeed app for Android not working.

**Comment by adolfintel** [comment]
Certbot issue again, it's fixed now.

**Comment by mrtaxi** [comment]
> Certbot issue again, it's fixed now.

Thank you!

**Comment by mrtaxi** [comment]
Not working again

**Comment by mrtaxi** [comment]
> Certbot issue again, it's fixed now. Seems to not working again

**Comment by adolfintel** [comment]
Fixed it again. This time it had a good reason to break, the disk was absolutely full. It looks like the project had a surge in popularity and is serving almost 100 tests per second at the moment 🤯

I had to delete all results from the database because it was almost 100G
