### ISSUE TITLE
AppID changed

### ISSUE THREAD

**Issue by licaon-kter** [librespeed/speedtest-android#5]
...on purpose, right?

FYI I fixed it for F-Droid: https://gitlab.com/fdroid/fdroiddata/commit/4a019d767c22722fc8ede78fb5b6d927d26d0a78#10eff4d8b13f8b4a6d6a94aaa0e7de205dd67b12

**Comment by adolfintel** [comment]
The version on F-Droid must be built from the mydemo branch. The master branch is a template.

**Comment by licaon-kter** [comment]
We build Tags, you tag whatever you want, branch or whatever.

Why did you mention branches exactly?

**Comment by adolfintel** [comment]
I tag them as demo-x.x.x

**Comment by licaon-kter** [comment]
Oh, right, I'll take another look.

**Comment by adolfintel** [comment]
You can just build it, if the splash screen says YOUR LOGO HERE, you're building the wrong branch.

**Comment by licaon-kter** [comment]
Ok, got it, the problem was that fdroidcheckupdate can't handle suffix/prefix, so it updates to `commit: demo-demo-1.1.2' so we need to disable that and add future versions manually.

Now, I see that 1.1.2 (non-demo) was successfully build](https://f-droid.org/wiki/page/com.dosse.speedtest/lastbuild_4), is there an issue with it to keep it (besides the "your app name here banner") or do we need to remove it?

**Comment by adolfintel** [comment]
If it was built from the template, then you should delete it because it's missing the list of servers and the privacy policy.

I'll update the manifest manually for future versions.

**Comment by adolfintel** [comment]
Did you fix this? I noticed that F-Droid is now distributing the template instead of the proper version

**Comment by licaon-kter** [comment]
It was already build, I've modified the metadata to hopefully disable the current one and build the correct one. Next cycle...
