### ISSUE TITLE
Custom Speedtest server not worked

### ISSUE THREAD

**Issue by MG-100** [librespeed/speedtest-android#8]
Hello,
I implemented my speedtest in the android app and when i ckick start then come 'An error occuredd'.

**Comment by adolfintel** [comment]
It's probably just a config error. Send me your JSON files at info@fdossena.com and I'll see what I can do.

**Comment by MG-100** [comment]
Hello,
I found the issue, the app doesnt support HTTPS.
My speedtest Server Support only HTTPS, After I enable http the speedtest Server working  in the app

**Comment by adolfintel** [comment]
The app does support HTTPS, make sure the server has a valid certificate.

**Comment by MG-100** [comment]
My Servers habe a ssl Zertifikat from Lets Encrypt. On the Website function all server with all in the app not

**Comment by MG-100** [comment]
My Servers habe a ssl Zertifikat from Lets Encrypt. On the Website function all server with all in the app not

**Comment by adolfintel** [comment]
That's very strange. Please send me the address of your test point if you can, so I can debug this

On December 12, 2019 8:39:47 PM GMT+01:00, MG_100 <notifications@github.com> wrote:
>My Servers habe a ssl Zertifikat from Lets Encrypt. On the Website function all server with all in the app not
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/librespeed/speedtest-android/issues/8#issuecomment-565154327
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MG-100** [comment]
Okay, 
fi-01.puh-speedtest.de

**Comment by adolfintel** [comment]
It works fine here. This is my ServerList.json file:
```
[
    {
        "name":"Test",
        "server":"https://fi-01.puh-speedtest.de",
        "dlURL":"garbage.php",
        "ulURL":"empty.php",
        "pingURL":"empty.php",
        "getIpURL":"getIP.php"
    }
] 
```
