### ISSUE TITLE
Issue with making my own server work on the app

### ISSUE THREAD

**Issue by Gokuofuin** [librespeed/speedtest-android#9]
Hi there

I know I'm probably doing something stupid but for the life of me I cannot get the server working on my own custom version of this software.

I have the normal web version working just fine (dantecampbell.org/speedtest)
But I cannot get the android app to use that as a server, these are my servers settings in the android app:
{
        "name":"mytestserver",
        "server":"http://dantecampbell.org/speedtest",
        "dlURL":"backend/garbage.php",
        "ulURL":"backend/empty.php",
        "pingURL":"backend/empty.php",
        "getIpURL":"backend/getIP.php"
    }

Please if any of you see something obvious I am missing help me.

**Comment by adolfintel** [comment]
Hi,
It seems like your server is sending a 301 redirect, which is not supported by the android app.

If you need additional troubleshooting, contact me at info@fdossena.com, issues are for bug reports and such.
